# Generated by Django 5.2.6 on 2025-09-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photograph_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
