# Generated by Django 5.2.6 on 2025-09-15 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photograph_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='date_upload',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
