# Generated by Django 5.2.6 on 2025-09-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_photograph_date_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='photo_path',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
