# Generated by Django 5.2.6 on 2025-09-18 13:52

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_photograph_photo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='photo_path',
            field=models.ImageField(upload_to=gallery.models.photo_upload_to),
        ),
    ]
