# Generated by Django 5.2.6 on 2026-05-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_photograph_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photograph",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
